Add WASM doom game example in Docker Compose file
redhat-developer/podman-desktop-demo pull request #43
Opened 2024-06-13 13:50 UTC by cedricclyburn

It is fun to demo :)

2024-06-13 13:53 UTC, slemeur commented
This is great @cedricclyburn ! Maybe, we should have a small readme to explain how to run it?

2024-06-13 14:45 UTC, cedricclyburn commented
Sure thing! Added @slemeur

2024-06-13 19:11 UTC, benoitf approved these changes

2024-06-13 19:51 UTC, cdrage requested changes

2024-06-13 19:51 UTC, cdrage commented on wasm/doom/README.md
> +podman-compose up
```suggestion
podman compose up
```

2024-06-13 19:51 UTC, cdrage commented on wasm/doom/README.md
> +To run the game, you need to have [Podman](https://podman.io/) installed, and the [`podman-compose`](https://github.com/containers/podman-compose) script available (included in Podman Desktop).
should not link to `podman-compose` as we are prefering `podman compose` now using the compose binary

2024-06-18 16:26 UTC, cedricclyburn commented
Awesome should be good to go!

2024-06-19 05:44 UTC, slemeur approved these changes

2024-06-19 05:44 UTC, slemeur commented
Thanks @cedricclyburn !!

2024-06-19 05:44 UTC, merged